### ISSUE TITLE
Nesting belongsTo and hasMany

### ISSUE THREAD

**Issue by miketownsend** [lytics/ember-data.model-fragments#107]
Kiaora! 
I'm trying to nest a relationship to a record (not a fragment) but it doesn't seem to be supported.
Can you please confirm that this is / is not supported? If not, are there any plans to support it?

```
Post = DS.Model.extend({
  title: DS.attr('string'),
  html: DS.attr('string'),
  comments: DS.hasManyFragments('comment')
});

Comment = DS.ModelFragment.extend({
  message: DS.attr('string'),
  author: DS.belongsTo('user', { async: true})
});
```

Thanks heaps for this resource by the way :-)

Mike Townsend

**Comment by chrisvariety** [comment]
Not supported currently, check out #18 for more info.

**Comment by miketownsend** [comment]
Thanks Chris, I'll use a computed property work around for now!
