### ISSUE TITLE
Simplify fragment API naming

### ISSUE THREAD

**Issue by slindberg** [lytics/ember-data.model-fragments#11]
`DS.ModelFragment`, `DS.hasOneFragment`, and `DS.hasManyFragments` are all mouthfulls. The tradeoff is always clarity vs. brevity, and the current naming may be a little too heavy on the clarity side. Potential simplifications:

`DS.ModelFragment` → `DS.Fragment`
`DS.hasOneFragment` → `DS.fragment`, `DS.fragmentObject`
`DS.hasManyFragments` → `DS.fragments`, `DS.fragmentArray`

 Moving away from likeness to `DS.belongsTo` and `DS.hasMany` may be desirable once all relationship properties return promises, which fragment properties will never do.

**Comment by mmadden** [comment]
+1

May I suggest DS.fragment and DS.fragmentCollection?

**Comment by jakesjews** [comment]
I'm thinking about making a PR for this issue. Do you still like DS.Fragment, DS.fragment, and DS.fragments? It might be a little confusing with [Ember.Fragment](https://github.com/ef4/rfcs/blob/element-and-fragment/active/0000-element-and-fragment.md) but I don't think it would be too bad if it's in the DS namespace.

**Comment by slindberg** [comment]
I'm going to be doing a lot of work on MF in the coming weeks to make it compatible with the [recently merged `references` branch](https://github.com/emberjs/data/pull/3094), and I'd like to tag the result as `v1.0` to fall in step with ember data.

I'd also like to settle on an API before then, ideally creating a new `v0.3.4` release with deprecation warnings for any API changes, so that we don't have to carry `DS.hasOneFragment` and `DS.hasManyFragments` around forever.

It'd be great to find out what active contributors/users think about what the 1.0 API should look like:

@igorT, @chrisvariety, @knownasilya, @kielni, @Glavin001, @workmanw, @blimmer, @mbrakken, @sparkrevolutions, @elwayman02, @snovity

Please cc anyone else on this thread that you know is actively using MF!

**Comment by knownasilya** [comment]
I like the proposed naming changes. Apart from that I would love to be able to pass a nested object/array on creation and have it create all of the child fragments automatically..

**Comment by Glavin001** [comment]
> DS.ModelFragment → DS.Fragment
DS.hasOneFragment → DS.fragment, DS.fragmentObject
DS.hasManyFragments → DS.fragments, DS.fragmentArray

+1 for proposed renamed APIs.  Thanks for keeping us all in the loop!

**Comment by slindberg** [comment]
To be clear, I don't want to alias fragment properties. I'm mainly considering renaming the properties to one of the following options:

    DS.hasOneFragment   → DS.fragment
    DS.hasManyFragments → DS.fragments

OR

    DS.hasOneFragment   → DS.fragment
    DS.hasManyFragments → DS.fragmentArray

@mmadden While perhaps more descriptive, `fragmentCollection` is a bit of a mouthful, and one of the main reasons for an API rename would be to focus on letter-brevity.

I'm still on the fence about `DS.ModelFragment → DS.Fragment`

**Comment by igorT** [comment]
It shouldn't be DS, as ModelFragments should just be an ember addon and not reuse ED's namespace

**Comment by igorT** [comment]
:+1:  for `fragment` and `fragmentArray`

**Comment by knownasilya** [comment]
I'm in the same boat as @igorT

**Comment by elwayman02** [comment]
I like ```fragment``` and ```fragments```, but I agree that there should be a separate namespace for the addon and not hijack Ember-Data.  It'd be nice to use a destructuring import in ES6 to just import what we need:

```import { fragment, fragments } from ...```

**Comment by dfreeman** [comment]
I like `fragment` and `fragmentArray`.

On the namespace front, rumor has it Ember/ED are going to be moving to more modularized distributions in the future so that you'd import, e.g., `attr` and `Model` directly. Dockyard even recommends assigning such things to module-local variables up front in their [style guide](https://github.com/dockyard/styleguides/blob/master/ember.md#create-local-version-of-ember-and-ds) in preparation for that change.

Given that, I'm :+1: to @igorT's comment on getting out of the DS namespace, and I probably prefer `ModelFragment` to just `Fragment`.

**Comment by devinus** [comment]
What @igorT said also `fragment` and `fragmentArray` (`fragments` is just asking for trouble).
