### ISSUE TITLE
should detect if methods its providing are already provided

### ISSUE THREAD

**Issue by stefanpenner** [lytics/ember-data.model-fragments#116]
for example: https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/ext.js#L14-L24

This will allow for fail-fast scenarios if ED and MF ever conflict in API.

**Comment by stefanpenner** [comment]
some of this may be fixed on [this long running branch](https://github.com/lytics/ember-data.model-fragments/pull/109) its worth applying any missing changes to that branch/pr

**Comment by slindberg** [comment]
Is there a better way to detect the existence of a method on the prototype than

```js
DS.Store.proto();

if (DS.Store.prototype.createFragment) {
  // ...
}
```

**Comment by slindberg** [comment]
The only API that model fragments adds to `DS` now is `store#createFragment`, which I consider very low-risk.
