### ISSUE TITLE
usage of deprecated/removed features

### ISSUE THREAD

**Issue by stefanpenner** [lytics/ember-data.model-fragments#117]
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/ext.js#L156
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/model.js#L137
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/model.js#L187

A quick work-around in a lib that must support many versions of ember is to define a keys helper:

the following should suffice.

```js
var keys = Object.keys || Ember.keys;
```

- [ ] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/transform.js#L9

```js
var isArray = Array.isArray || Ember.isArray;
```

Enumerable utils are no more in ember 2.0, as it only supports ES5+ browsers.

- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/transform.js#L10
- [x] https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/array/fragment.js#L10
This one, we will likely provide an EnumerableUtils polifill, but easiest thing would be to quickly drop an inline polifill

```
function map(collection, fn) {
  var result = new Array(collection.length);
  for (var i = 0; i< collection.length; i ++) {
    result[i] = fn(collection[i])
  }
return result;
}
```

Or decide IE8 support is to be dropped – I'm not sure what this project aims to be compatible with.

**Comment by stefanpenner** [comment]
some of this may be fixed on [this long running branch](https://github.com/lytics/ember-data.model-fragments/pull/109) its worth applying any missing changes to that branch/pr

**Comment by slindberg** [comment]
The `Ember.keys` and `Ember.EnumerableUtils` deprecations have been resolved, but I'm not so sure about the `Ember.isArray` case. Since it's not just a simple polyfill for `Array.isArray`, I would be breaking backwards compatibility in instances where a fragment array property is set to an array-like object like `Ember.ArrayProxy`.

AFAIK, `Ember.isArray` isn't being deprecated; is there a better way to do array-like detection that I'm not aware of?
