### ISSUE TITLE
How to add a fragment to an already existing record

### ISSUE THREAD

**Issue by Forster-Groux** [lytics/ember-data.model-fragments#129]
Hi

I have a model like this:

```
Cluster = DS.Model.extend({
  name  : DS.attr('string'),
  nodes : DS.hasManyFragments('node')
});

Node = DS.ModelFragment.extend({
  name : DS.attr('string'),
});
```

I want to store a node from a form that belongs to an existing cluster.

The endPoint from my backend API to add a node to a cluster looks like this:

> POST .../api/v1/cluster/:cluster_id/nodes

What i do:

In the route for the node form:

```
model: function() {
  return this.store.createFragment('node');
},
```

In the controller that handles the form:

```
actions: {
  submit: function() {
    this.get('model').save();
  },
}
```

But on submit all i get is:
> Uncaught Error: Attempted to handle event `willCommit` on [someEmber objet] while in state root.loaded.created.

And the API endPoint is not even called.

What is the best way to perform this action?.

**Comment by slindberg** [comment]
I do not recommend returning model fragments from route `model` hooks. In this case you should return the cluster as the model, and in your `submit` action you should create the fragment and save the cluster:

```js
actions: {
  submit: function() {
    var cluster = this.get('model');

    cluster.get('nodes').createFragment({
      name: this.get('nodeName')
    });

    cluster.save();
  },
}
```
