### ISSUE TITLE
Question: A way to create fragment w/o store?

### ISSUE THREAD

**Issue by sedouard** [lytics/ember-data.model-fragments#131]
Quick question, is there a way to simply add an object which resembles a fragment to a model, rather than bringing in a reference to the store?

I have a component which I need to create fragments, but I really didn't want to bring in a reference to the store, if I don't need to.

**Comment by slindberg** [comment]
TL;DR not at the moment, see #10

If you are using a `hasManyFragments` property, you can use the `createFragment` method of the fragment array without needing access to the store. But using a `hasOneFragment` property you are forced to create a new fragment using the store.

Once #10 is addressed, you will be able to set fragment properties using object literals directly, avoiding the need for the store.
