### ISSUE TITLE
Moving fragment from one collection to another

### ISSUE THREAD

**Issue by martinthogersen** [lytics/ember-data.model-fragments#132]
I'm using this code, to move a record from one collection to another. However, it throws this error: *Fragments can only belong to one owner, try copying instead*

```js
      currentSection.get('applicationQuestions').removeFragment(question)
      newSection.get('applicationQuestions').addFragment(question)
```

After reviewing the code, I can see that the code is checking if the _owner is set. Unsetting that value seems to fix the problem:

```js
      currentSection.get('applicationQuestions').removeFragment(question)
      question._internalModel._owner = undefined
      newSection.get('applicationQuestions').addFragment(question)
```

What's the intended way to move a record from one collection to another?

**Comment by slindberg** [comment]
I can see why this is confusing. This warning was intended to prevent assigning a fragment to multiple owner records. Fragment owners thus far do not change once they are set, however when removing a fragment from a record as you are doing, it should be possible to reset the internal `_owner` reference and allow it to be added to another record. I've opened a new issue to track this: #133

> What's the intended way to move a record from one collection to another?

For now, just add a copy of the fragment

```js
currentSection.get('applicationQuestions').removeFragment(question)
newSection.get('applicationQuestions').addFragment(question.copy())
```
