### ISSUE TITLE
Child fragments don't update values during save based on server response

### ISSUE THREAD

**Issue by richardbowman** [lytics/ember-data.model-fragments#136]
Made a simple app that shows the issue.

https://github.com/HelloWallet/fragment-update-failure

Basically, when the server provides new values for attributes in child fragments, they don't update with the new value. However, if you do a rollback, the new values will be applied.

This is not how Ember Data works on the top-level model. When attributes are updated by the server as a result of the save operation, they should be immediately applied to the client-side model.

**Comment by slindberg** [comment]
Looks like this is happening when a record is created. Thanks for reporting & making test repo :+1:

**Comment by slindberg** [comment]
Fix released in v0.4.2
