### ISSUE TITLE
Assertion Failed: The `JSONAPISerializer` is not suitable for model fragments

### ISSUE THREAD

**Issue by christophermlne** [lytics/ember-data.model-fragments#140]
```Error while processing route: form.show.index Assertion Failed: The `JSONAPISerializer` is not suitable for model fragments, please use `JSONSerializer```

Will ember-data.model-fragments work with the new Ember data JSONAPISerializer?

This would be a problem as I am using the json_api_resources gem on the backend. 
Is it possible yet to use this Ember addon in conjunction with a project that is trying to adhere to the JSON Api specification?

Many thanks, this addon is incredible so far.

**Comment by christophermlne** [comment]
I was just reading through a few threads trying to get some background on this issue. Looks like you already answered this question here: https://github.com/lytics/ember-data.model-fragments/issues/110#issuecomment-142386315 

>@jackweinbender Yes, this project is intended to be 100% compatible with DS.JSONAPISerializer, in exactly the way the spec states. Just put your nested JSON in the attributes hash, and declare the correct fragment attributes and you're done. Note however that model fragment serializers themselves cannot extend DS.JSONAPISerializer, since their raw response is not a full JSON API document (it is simply the specified attribute's raw value).

You can close this. Hopefully this helps others who might be looking for a solution to the same issue.

**Comment by slindberg** [comment]
:+1:

I'm sure you saw it, but just in case [I opened another issue](https://github.com/lytics/ember-data.model-fragments/issues/135) to make it easier for apps that have an application serializer the extends from `DS.JSONAPISerializer`.
