### ISSUE TITLE
Fragment Arrays Not Correctly Updated When Adding New Item

### ISSUE THREAD

**Issue by dwolfand** [lytics/ember-data.model-fragments#142]
When saving a model with a child array, if the server returns updated array children and adds an additional item, it does not update the data of the existing children in the model.

Please see https://github.com/dwolfand/fragment-update-failure/tree/child_array_issues for the example app.

Also, since this is an issue with the current master build of model fragments, make sure to replace the contents of the dist folder in bower_components/ember-data.model-fragments with the distributable files built from master.

**Comment by richardbowman** [comment]
Just checking in here, this is basically a follow-up issue to issue 136. We took the corrected master version and used it, but it seems to have a follow-up issue related to arrays that @dwolfand found. It is definitely a big problem for our applications, for now, we reverted to 0.4.1, and added rollbacks after all saves for now.

**Comment by slindberg** [comment]
Turns out this case was being tested in the fix for #136, but the test was broken due to some copy-pasta laziness :sob:

Thanks for reporting @dwolfand, hopefully get a release out soon.

**Comment by slindberg** [comment]
Fix released in v0.4.2
