### ISSUE TITLE
Deserializing fails

### ISSUE THREAD

**Issue by acerov** [lytics/ember-data.model-fragments#154]
Hi,

It looks to me that if attribute is not set during createFragment, and if later in persisting process server sets the attribute and returns it in json, that attribute is not deserialized.
I am still in debug phase so I am not 100% sure

**Comment by acerov** [comment]
I checked litle bit further, it is not deserializing even when I set attribute, server sends ne value for that attribute but it remains the same.

I am using ember 1.13.9 and ember-data 1.13.14

**Comment by acerov** [comment]
My error, the server was returning JSON with different names for fragments, fixed that and deserializing works fine

**Comment by slindberg** [comment]
:+1:
