### ISSUE TITLE
Model does not detect itself as dirty after setting the model fragment attribute

### ISSUE THREAD

**Issue by leondmello** [lytics/ember-data.model-fragments#155]
https://github.com/leondmello/ModelFragment

Just run this app with ember serve and load it in the browser and then click the button with the console open.

Here's the gist of what I am trying to do,
1. A model has a fragment attribute with some values, set this attribute to null. Check if the model is dirty. (This returns true as expected)
2. I then use the set method on the model to set the fragment to new values (different from the original ones). A dirty check on the model should return true. But it returns false.

I have give a link of the app I wrote to test this. The code which performs the steps I have mentioned is in the settings controller.
Maybe I am setting the fragment attribute incorrectly

**Comment by slindberg** [comment]
Thanks for reporting, this does appear to be a bug. Thanks as well for creating a repro-repo :+1:

**Comment by slindberg** [comment]
This is related to the object literal notation introduced in v0.4.1. For now, setting fragment properties to newly created fragments (using `store.createFragment(...)`) works correctly.

**Comment by leondmello** [comment]
Oh, well I face this issue in a component. So I cannot access the store. 
Is there an alternative?
Were you able to identify where the issue is. I don't mind submitting a pull request.

**Comment by slindberg** [comment]
The store is a service, so you can inject it with `Ember.inject.service('store')`.

**Comment by leondmello** [comment]
Oh, cool. I'm still an ember newbie learning the ember ways :)

**Comment by leondmello** [comment]
From what I read, injecting the store into components is not recommended. I'll make do with that for now.

**Comment by workmanw** [comment]
@leondmello 

> From what I read, injecting the store into components is not recommended. I'll make do with that for now.

I think people are still trying to figure out the best patterns for life without controllers. Some "what's recommended" is still kind of in flux. But IMHO if you have an app with any level of moderate complexity, using the store's service in a component is the only way to keep your sanity.
