### ISSUE TITLE
Rolling back doesn't reset hasManyFragments fields with Ember Data Beta 12

### ISSUE THREAD

**Issue by jakesjews** [lytics/ember-data.model-fragments#31]
Hello, it looks like properties within hasManyFragments objects aren't being reset during a rollback. We are using ember data beta 12 so this may be the cause of the problem.

The project's tests pass with beta 7 but when I update to beta 12 there are several test failures which seem related to the issue.

It's possible this is caused by breaking changes in Beta 12 related to observing the model's data property described [here](http://emberjs.com/blog/2014/11/24/ember-data-1-0-beta-12-released.html).

Here's a link to a [JSbin showing the problem](http://emberjs.jsbin.com/vanazimevu/2/edit).

**Comment by blimmer** [comment]
I read on [this PR](https://github.com/lytics/ember-data.model-fragments/issues/42) that the fix for this will only support ED 1.14(.1) . Any updates on the timing of this fix?

**Comment by slindberg** [comment]
I am currently in the process of publishing a fix, hold tight.

**Comment by slindberg** [comment]
v0.2.4 is now compatible with ED >= v.1.0.0-beta.14, thanks @igorT.

**Comment by blimmer** [comment]
thank you!
