### ISSUE TITLE
Cant access hasManyFragment array from model computed property

### ISSUE THREAD

**Issue by sparkrevolutions** [lytics/ember-data.model-fragments#42]
Am I right in assuming that we cannot access fragment content from a computed property on the parent model?

I removed my actual logic and simplified the return to just the array length,and with the following code I  get `0` returned when the `lines` property on the order model is populated.

```javascript
// /models/order.js
import DS from 'ember-data';

export default DS.Model.extend({
    rev: DS.attr('string'),
    lines: DS.hasManyFragments('order-line',{defaultValue: []}),
    comment: DS.hasOneFragment('order-comment'),
    type: DS.attr('string', {defaultValue: 'order'}),
    origin: DS.attr(),
    orderTotal: function(){
      var lines = this.get('lines.length');
      return lines;
    }.property('lines')
});


// /models/order-lines.js
import DS from 'ember-data';

export default DS.ModelFragment.extend({
  productCode: DS.attr('string'),
  productTitle: DS.attr('string'),
  quantity: DS.attr('string'),
  quantityBalance: DS.attr('string'),
  price: DS.attr('string'),
  discount: DS.attr('string'),
  status: DS.attr('string'),
  notes: DS.attr('string'),
  revised: DS.attr('string', {
    defaultValue: function() { return Date.now (); }
  }),
  lineTotal: function(){
    var total = parseFloat(this.get('price')) * parseFloat(this.get('quantity'));
    return total.toFixed(2);
  }.property('price', 'quantity')
});
```

```html
<!-- /templates/order-summary.hbs -->
          <tfoot>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td colspan="2"><strong>Order Total</strong></td>
              <td colspan="2">{{controllers.customers.currentOrder.orderTotal}}</td>
            </tr>
          </tfoot>
```

n.b. `currentOrder` is a saved Order record.

**Comment by slindberg** [comment]
> Am I right in assuming that we cannot access fragment content from a computed property on the parent model?

No, this is definitely possible. Your `orderTotal` computed property must declare a dependent key that observes the array's length, like `lines.length`, [`lines.[]`](http://emberjs.com/api/classes/Ember.Array.html), or [`lines.@each.foo`](http://emberjs.com/guides/object-model/computed-properties-and-aggregate-data/).

Also note that this project is [not compatible with ED v1.0.0-beta.12](https://github.com/lytics/ember-data.model-fragments/issues/31#issuecomment-66547111) (and never will be -- support will skip straight to beta.14).

**Comment by sparkrevolutions** [comment]
Literally just was about to correct myself. Sorry - not quite recovered from new years yet :beers: 

Thank you for your clarification anyway
