### ISSUE TITLE
This project is not yet compatible with Ember Data v1.0.0-beta.12

### ISSUE THREAD

**Issue by dukedave** [lytics/ember-data.model-fragments#43]
Could the readme possibly expand on:

> This project is not yet compatible with Ember Data v1.0.0-beta.12

I.e. what at the implications of this, and how do we avoid them.

I'm fairly new to ember, and I've got an ember-cli app with `ember-data` at ` "1.0.0-beta.14.1"` (in both my `package.json` and `bower.json`, but I'm not sure how to downgrade correctly.

**Comment by slindberg** [comment]
v0.2.4 is now compatible with >= 1.0.0-beta.14. You should now also be able to install this project as an ember-cli addon, see the readme.
