### ISSUE TITLE
Unable to install model fragments w/ 0.1.5 and ember-data beta.14.1

### ISSUE THREAD

**Issue by thoov** [lytics/ember-data.model-fragments#49]
If I create a blank project with ember-cli v0.1.5 and update ember-data to beta.14.1 the app will load up just fine. However, after running:

```
ember install:addon ember-data-model-fragments
```

I get this error in the browser:

```
Uncaught ReferenceError: define is not defined
```

Not sure if I'm the only one getting this or if this is happening to others?

**Comment by slindberg** [comment]
Can you give more detailed steps? It appears to work for me™

```sh
$ npm cache clear
$ bower cache clean
$ ember new app && cd app
version: 0.1.5
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/.gitkeep
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
```

then

```sh
$ ember install:addon ember-data-model-fragments
version: 0.1.5
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/components/ember-data.git#1.0.0-beta.12
  cached git://github.com/components/ember-data.git#1.0.0-beta.12
  new version for git://github.com/components/ember-data.git#~1.0.0-beta.7
  resolved git://github.com/components/ember-data.git#1.0.0-beta.14.1
Installed browser packages via Bower.
```

**Comment by knownasilya** [comment]
What's `The globPattern "undefined" did not match any files, so no file updates will be made.`?

**Comment by thoov** [comment]
@slindberg those steps work for me and the app appears to "build" but when I visit http://localhost:4200 then I get that error:

```
Uncaught ReferenceError: define is not defined
```

**Comment by slindberg** [comment]
Turns out that #52 doesn't solve the issue of the wrong blueprint being invoked with `install:addon`. [I filed an issue over at ember-cli](https://github.com/ember-cli/ember-cli/issues/2915) that's been fixed already, so this should be resolved in the next release of ember-cli.

**Comment by slindberg** [comment]
I added a note to the readme indicating that `install:addon` cannot yet be used.

**Comment by trabus** [comment]
Sorry about `The globPattern "undefined" did not match any files` warning, it was [happening with any blueprint that didn't have files in it](https://github.com/ember-cli/ember-cli/issues/3142). 
The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13.

**Comment by slindberg** [comment]
:+1:
