### ISSUE TITLE
DS is not defined

### ISSUE THREAD

**Issue by jrhe** [lytics/ember-data.model-fragments#61]
After following the standard install instructions I get the following error in the development console

`Uncaught ReferenceError: DS is not defined`

This seems to be because ember-data isn't necessarily loaded before ember-data.model-fragments is loaded.

A quick fix is adding the following into Brocfile.js, after importing ember data:
`app.import('bower_components/ember-data.model-fragments/dist/ember-data.model-fragments.js');`

After working this bug through with @igorT he has suggested to do the above as part of the ember generate step.

**Comment by slindberg** [comment]
Hm, seems like an ember-cli addon dependency issue to me. You should definitely not need to add `app.import(...)` to your Brocfile.js to import, since the [addon does it](https://github.com/lytics/ember-data.model-fragments/blob/master/ember-addon/index.js#L9-L12) and could possibly result in duplicated code in the build.

My understanding is that ember-cli used bower dependencies to manage addon dependencies (including import order), but perhaps that's not the case. I'll look into it.

**Comment by igorT** [comment]
It actually crashes if we have the npm package installed at all. Had to rm -rf the package from node_module to get it to work

**Comment by slindberg** [comment]
You mean running `ember serve` bails out? Was there a stack trace? What version of ember-cli are you using? Does it work like expected after doing a nom, or does `ember` fail unless you `rm -rf node_modules/ember-data-model-fragments`? Doing a fresh install locally seems to work fine:

```sh
$ ember --version                                                                                                                                                                                                                                                              9:17:51 AM
version: 0.1.12
node: 0.10.35
npm: 2.1.8
$ ember new test-app && cd test-app
# ...
$ ember install:addon ember-data@1.0.0-beta.14.1
# resolve conflict by choosing ember-data 1.0.0-beta.14.1
$ ember install:addon ember-data-model-fragments
# ...
$ ember build
version: 0.1.12
Built project successfully. Stored in "dist/".
```

Running `ember serve` and going to `http://localhost:4200/` in a browser, I don't get any errors (although I did see that the version reported in the debug output is incorrectly showing `0.2.7`, oops).

**Comment by slindberg** [comment]
It looks like adding an `after` key to the `ember-addon` property in package.json might do the trick. @jrhe would you mind adding this line manually to `node_modules/ember-data-model-fragments/package.json`, and then rebuild to see if it's included in the right order?

```json
{
  ...
  "ember-addon": {
    "main": "ember-addon/index.js",
    "after": "ember-data", <---
    "defaultBlueprint": "ember-data-model-fragments"
  },
  ...
}

```

**Comment by igorT** [comment]
This seems like an older app, and it seems like it was including ember-data in the Brocfile as well, so we needed to put model fragments there as well. Probably as ember-cli evolved this has changed. Not sure I want to debug this tbh.

**Comment by slindberg** [comment]
:+1: 

If `ember-data` is added via Brocfile.js, it probably isn't an addon dependency in package.json, in which case I would recommend removing `ember-data-model-fragments` from package.json as well, since the build artifacts use Bower anyway.

**Comment by gitmarkscode** [comment]
Hey, I am getting this error and I don't understand how you guys resolved this issue. can you please explain steps to get fix?

    "ember-cli": "2.3.0-beta.1",
    "ember-data": "^2.3.0",
    "ember-data-model-fragments": "2.1.1",

**Comment by gitmarkscode** [comment]
NVM, if you're using Ember data 2.3 and getting `Uncaught ReferenceError: DS is not defined` https://github.com/lytics/ember-data-model-fragments/issues/174  go here.
