### ISSUE TITLE
After Ember data moved to snapshots serialization doesn't work anymore

### ISSUE THREAD

**Issue by snovity** [lytics/ember-data.model-fragments#65]
Like described here https://github.com/emberjs/data/blob/master/CHANGELOG.md#serializerserialize-now-receives-a-snapshot-instead-of-a-record-instance serializer now uses `attr` instead of `get` and fragments do not have an `attr` method.

**Comment by slindberg** [comment]
The only modification to `DS.Model` (and therefore `DS.ModelFragment`) is the [private `_createSnapshot` method](https://github.com/emberjs/data/pull/2623/files#diff-4cc9f4885e8425eeaa555ef3648588ae). The `attr` method you mention belongs to the [new snapshot object](https://github.com/emberjs/data/pull/2623/files#diff-d8a3fdbb89d6cf0bb2b162ed7d3b76ff), which is completely separate from `DS.Model`. Follow the update to beta.15 at #64.

**Comment by snovity** [comment]
Ok, thanks! :)
