### ISSUE TITLE
Latest ED breaks model fragments

### ISSUE THREAD

**Issue by igorT** [lytics/ember-data.model-fragments#67]
Model fragments need to implement snapshot creation, for the new store apis to work

**Comment by dwickern** [comment]
Here's a workaround
```
DS.ModelFragment.reopen({
    _createSnapshot: function() {
        return new DS.Snapshot(this);
    }
});
```

**Comment by slindberg** [comment]
#66 adds support for snapshots. @dwickern if you are using your workaround in an app, could you test it against the [`tmp-dist`](https://github.com/lytics/ember-data.model-fragments/pull/64#issuecomment-74924591) branch instead?

**Comment by dwickern** [comment]
@slindberg LGTM

**Comment by slindberg** [comment]
@dwickern Thanks for checking against your app. This probably won't change anything unless you are doing something fancy with fragments in the parent record's serializer, but [I've altered how fragment snapshots behave in the update PR](https://github.com/lytics/ember-data.model-fragments/pull/66#issuecomment-75131218).

**Comment by joelalejandro** [comment]
This issue should be closed, as #68 and v0.3.0 solved it.

**Comment by artzte** [comment]
Thanks for the quick action on this.

**Comment by slindberg** [comment]
:+1:
