### ISSUE TITLE
ember-cli blueprint not working correctly when --pod is set

### ISSUE THREAD

**Issue by chopper** [lytics/ember-data.model-fragments#73]
The ember-cli generator names the file incorrectly when run with the `--pod` flag. 

For example, when running `ember generate fragment hello-world --pod` creates the file in
```
app/pods/hello-world/fragment.js
```
instead of
```
app/pods/hello-world/model.js
```

Additionally the blueprint always generates .js files instead of .coffee when ember-cli-coffeescript is installed.

**Comment by slindberg** [comment]
Fixed this in #74 which will go out in the next release (as soon as #72 is resolved). I don't use coffeescript, but PRs are always welcome :smile:
