### ISSUE TITLE
Warning in Ember-cli 0.2.1

### ISSUE THREAD

**Issue by chrisvdp** [lytics/ember-data.model-fragments#76]
When I do any action on the command line with `ember`, running 0.2.1 I get the following:

    The package `ember-data-model-fragments` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/username/Web/service/webui/node_modules/ember-data-model-fragments`. This is generally caused by an addon not having a `main` entry point (or `index.js`).

**Comment by slindberg** [comment]
This is fixed in master by #70, will create a new release shortly.

**Comment by chrisvdp** [comment]
Thanks

**Comment by slindberg** [comment]
Fixed in [v0.3.1](https://github.com/lytics/ember-data.model-fragments/releases/tag/v0.3.1).
