### ISSUE TITLE
`createFragment` is undefined in service unit test

### ISSUE THREAD

**Issue by charlesdemers** [lytics/ember-data.model-fragments#78]
I have a simple service:

```js
// my-service.js
import Ember from 'ember';

export default Ember.Service.extend({
  store: Ember.inject.service(),

  doSomething: function() {
    this.get('store').createFragment(...);
  }
});
```

All is well in my app, but when I try to unit test the service, the store is injected but `createFragment` is `undefined`. From looking at your code I think it’s because the `main` module isn’t executed in the context of a unit test. I just can’t figure out a way to execute it since no module is exposed to ember-cli.

Any idea how I could fix this?
Thank you!

**Comment by slindberg** [comment]
What does your test look like? Are you sure that it's not the store itself that is undefined? Remember if you are using `moduleFor`, you have to specify `service:store` as a dependency.

There's almost no situation where `store#createFragment` would exist in the app, but not in the test – it's a vendor lib that modifies Ember Data through the `DS` global.

**Comment by charlesdemers** [comment]
You’re right, the whole store isn’t defined... sorry about that, I’ve been struggling with dependency injection for a couple days now. Unfortunately adding `needs: ['service:store']` says I’m trying to register an unknown factory. Closing this, thanks for your help.

**Comment by slindberg** [comment]
:+1:

Also note: the store was only registered as a service recently in [beta.16](https://github.com/emberjs/data/commit/830aa08b7f5820674bf327457392b4867b3dc36f?diff=unified#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR78).
