### ISSUE TITLE
hasManyFragments ignoring array defaultValue

### ISSUE THREAD

**Issue by sparkrevolutions** [lytics/ember-data.model-fragments#82]
Hi,

I posted an issue related to defaultValue awhile back (#36). Using a empty array as the defaultValue solved the issue at the time.

Having now updated the project to 0.3.1, I receive the following error which I have tracked down to the initialisation of the "collection-product" fragment:

```Uncaught Error: Assertion Failed: A fragment array property can only be assigned an array or null```

Any ideas? Code below:

```javascript
// /models/collection.js
import DS from 'ember-data';

export default DS.Model.extend({
	rev: DS.attr('string'),
	type: DS.attr('string'),
	name: DS.attr('string'),
  products: DS.hasManyFragments('collection-product', {defaultValue: []}),
	meta: DS.hasOneFragment('collection-meta'),
  credentials: DS.hasManyFragments()
});
```

```javascript
// /models/collection-product.js
import DS from 'ember-data';

export default DS.ModelFragment.extend({
  product: DS.attr('string'),
  productCode: DS.attr('string'),
  productTitle: DS.attr('string'),
  order: DS.attr('string')
});
```
```javascript
// /controllers/collections-modal.js
    createCollection: function(){
      var collection = this.store.createRecord('collection');
      collection.set('meta', this.store.createFragment('collection-meta'));
      //error occurs on the line below
      collection.set('products', this.store.createFragment('collection-product'));
      collection.set('type', 'collection');
      collection.set('meta.creator', 'user');
      collection.set('meta.username', this.get('controllers.application.currentUser.object.user.name'));
    
      this.set('newUserCollection', {
        enabled: true,
        object: collection
      });
    },
```

Ember CLI: 0.2.2
Ember Data: 1.0 Beta 16
Ember: 1.11.0

**Comment by slindberg** [comment]
Is this happening when you are creating a new fragment, or when a record is being deserialized? Can you debug that error and see what the value is that is not an array or null?

There haven't been any recent changes that change default value behavior, so I'm guessing this is something else. Another possibility is that there was a subtle breaking change in beta.16, since I haven't upgraded to it yet. What version are you upgrading from?

**Comment by slindberg** [comment]
It looks like you are trying to assign a single fragment to a fragment array property:

```javascript
collection.set('products', this.store.createFragment('collection-product'));
```

Try something like:

```javascript
collection.set('products', [ this.store.createFragment('collection-product') ]);
```

**Comment by sparkrevolutions** [comment]
Thanks for getting back to me so quickly @slindberg. Your suggestion of wrapping the fragment in an array worked fine!

I think I understand your explanation. In a sense, I am overwriting the defaultValue with an object which obviously fails the Ember isArray method. On reflection, I don't actually need to create the fragment like this in my project as I am initialising it way before it actually gets some data.

Instead, I am now doing something like this:

'''javascript
      collection.get('products').createFragment({
        product: 'Clock',
      })
'''

Together with the default value, this works fine.

Maybe re-jigging the defaultValue example you have on the readme so the code where you demonstrate "Cannot read property 'createFragment' of null" does not reference the same model code above it, as that should actually work as depicted, unless I read the description between the two and imagine the default values were not present in the example model. Hope that makes sense!

**Comment by slindberg** [comment]
I think adding the fragment only once you know about its data is a much better approach.

Again though, I don't think this issue had anything do to with assigning a default value. The issue is the result of assigning a _single_ model fragment to a fragment _array_ property. Calling `set` on a `DS.hasMany` property isn't even valid; it's a convenience that it's possible to call `set` on a `DS.hasManyFragments` property, but it _must_ be an array-like object.

```javascript
    createCollection: function(){
      // The `product` property is initialized with the specified `defaultValue`
      // (an empty array) without issue
      var collection = this.store.createRecord('collection'); 

      // ...

      // Fails because a single fragment isn't array-like
      collection.set('products', this.store.createFragment('collection-product'));

      // ...
    },
```
