### ISSUE TITLE
ID attribute not available for nested fragments?

### ISSUE THREAD

**Issue by kcollignon** [lytics/ember-data.model-fragments#86]
We have a nested JSON document with a structure similar to:

```json
{
  "rates": {
    "name": "An example name",
    "updated_at": "2014-01-01",
    "artifacts": [
      {"id": "3242423423423", "name": "Artifact Name"}
      {"id": "2309943211455", "name": "Second Artifact"}
    ]
  }
}
```

In our template we are trying to iterate over the records and create a link to the nested artifact based on it's ID.

```javascript
each artifact in model.artifacts
  link-to "documents" model artifact
````

We can access all the other properties in the template, such as `artifact.name`, but whenever we call `artifact.id` we get undefined.

Any ideas how to access the ID property of the nested fragment object? I have verified that the ID property is getting returned in the data.

**Comment by slindberg** [comment]
This is probably happening in the [`normalizeId` method of `JSONSerializer`](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/serializers/json-serializer.js#L264), which you can override in a custom serializer for your fragment.

Since those embedded objects have (I assume) unique IDs, is there a reason you aren't just using the [`DS.EmbeddedRecordsMixin`](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html)?

**Comment by acerov** [comment]
@slindberg can you please explain little more how to access id in fragment.
I have the same problem, id on my fragment is null and in the same fragment in _InternalModel > _data > id is set correctly.

**Comment by slindberg** [comment]
@acerov I must stress first that if your nested JSON objects truly do have IDs, then you **should not** be using this project, and instead should use the `DS.EmbeddedRecordsMixin`.

With that said, ED [really](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/system/model/attributes.js#L328) [really](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/system/model/attributes.js#L62) doesn't want you using a `DS.attr` property named `id`. The best bet is to alias the attribute to something else in the `normalize` hook of your fragment serializer and declare an attribute with that name.

**Comment by ldong** [comment]
@slindberg I'm facing the same issue. The reason why I cannot use `EmbeddedRecordsMixin` is that, the parent does not observer children and grandchildren, Fragment is providing `rollbackAttributes` from top to bottom.

If for the `id`'s sake, is there a way to tell Ember data to observer children when use `EmbeddedRecordsMixin`? Thank you.
