### ISSUE TITLE
string fragments don't get defaults

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-data.model-fragments#88]
```js
//my-fragment.js
titles: DS.hasManyFragments()
```

```js
//my-parent-fragment.js
myFragment: hasOneFragment('my-fragment', {
  defaultValue: {
    titles: ['a', 'b']
  }
})
```

The default values are never set.

**Comment by knownasilya** [comment]
Have went through the source/console and could find no way to get those defaults..

**Comment by slindberg** [comment]
Not sure what the context of each of those snippets is... or what exactly is the issue. Here's [how default values work](https://github.com/lytics/ember-data.model-fragments#default-values):

```javascript
// app/models/thing.js
export default DS.ModelFragment.extend({
  titles: DS.hasManyFragments(null, { defaultValue: [ 'a', 'b' ] })
});
```

```javascript
var thing = this.get('store').createFragment('thing');

thing.get('titles') // [ 'a', 'b' ]
```

Note that [default values are only set on newly created records](https://github.com/emberjs/data/issues/678#issuecomment-32085835).

**Comment by knownasilya** [comment]
@slindberg sorry for being vague. I've updated my example above.

**Comment by slindberg** [comment]
Ah, I see now. This likely has to do with setting a default value for a nested fragment array. I'll look into this when I have some spare cycles.

**Comment by slindberg** [comment]
@knownasilya I added [a test case that covers this behavior](https://github.com/lytics/ember-data.model-fragments/pull/94). If you are able to reproduce this in a test, jsbin, etc. feel free to reopen.

**Comment by slindberg** [comment]
@knownasilya If this is not working for you, let's make it work. I just couldn't seem to reproduce the behavior you are seeing in a test. Can you take a look at the passing test case I linked to above and see if it is testing what you're trying to do?
