### ISSUE TITLE
ActiveModelSerializer and underscore keys

### ISSUE THREAD

**Issue by karellm** [lytics/ember-data.model-fragments#91]
I use the `ActiveModelSerializer` which transform underscore keys to camelCase. So if I have:

```javascript
export default DS.Model.extend({
  firstName : DS.attr('string'),
  lastName  : DS.attr('string')
});
```

I can pass it a payload like:

```javascript
{
  first_name: 'John',
  last_name: 'Doe'
}
```

But when I create a fragment like so:

```javascript
export default DS.ModelFragment.extend({
  firstName: DS.attr('string'),
  lastName: DS.attr('string')
});
```

And pass the same payload as previously, it does not seem to be normalized. It only works if I define it as:

```javacript
export default DS.ModelFragment.extend({
  first_name: DS.attr('string'),
  last_name: DS.attr('string')
});
```

Which obviously is totally inconsistent with the rest of my app. Any idea what I'm doing wrong here?

UPDATE: Here is my application serializer:

```javascript
export default DS.ActiveModelSerializer.extend();

```

**Comment by slindberg** [comment]
If you are using `ActiveModelSerializer`, you must be specifying a serializer for each of your models. [Model fragments get their own serializers](https://github.com/lytics/ember-data.model-fragments#serializing), so just do the same for your model fragments.

**Comment by karellm** [comment]
Ok gotcha. Any way to define it for all Fragments?

**Comment by karellm** [comment]
So creating a serializer worked well. Thanks for the pointer! Though it seems a little tedious to have to define one serializer per fragment.

For models, I actually only need a single `ApplicationSerializer` and all models inherit from it. I was hoping fragments would use my `ApplicationSerializer`. Would there be something similar for fragments?

**Comment by slindberg** [comment]
Hm, the [mechanism for looking up a serializer](https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/system/store.js#L1881) is the same for models and fragments, so it should be using your `ApplicationSerializer` if you aren't defining one for them. Can you reproduce this in a sample app?

**Comment by karellm** [comment]
@slindberg Sure, do you have a base jsfiddle or something available?

**Comment by slindberg** [comment]
No, I typically will just create an ember-cli project in a public github repo and then delete it afterwards. There isn't a great way to re-create ember-cli apps through jsbin/fiddle unfortunately :confused:.

If I was debugging my own app, I'd put a breakpoint in the `store#serializerFor` method and see what the lookup is actually returning.

**Comment by slindberg** [comment]
@karellm did you ever figure out why your app serializer wasn't getting used for fragments?

**Comment by karellm** [comment]
@slindberg Not yet but I have this in my todo list. We are working on a new release and it takes most of my time at the moment.

**Comment by karellm** [comment]
@slindberg I created a clean app to isolate the behaviour and you were right, it picks the `ApplicationSerializer` just fine! I will investigate the diff between the two apps and I find something I will post here. In the meantime, I don't think it is `ember-data.model-fragments` issue so I will close.

Thanks for the support!

**Comment by bakura10** [comment]
Hi,

I came across this issue and it apperas I have something similar. I defined my properties using camelCased, while my API returns underscore_key.

I have an application serializer that take care of the transformation using keyForAttribute. It works for Ember-Data managed models, however for fragments it does not work. It still requires my attributes to be called underscore_key in the model.

However, as soon as I'm explicitly creating a serializer for the fragment, it works.

May it be an incompatibility with latest Ember Data?

**Comment by slindberg** [comment]
@bakura10 there have been changes to the base class that auto-generated fragment serializers use since this issue was first opened. Read about them in the [serializing section of the readme](https://github.com/lytics/ember-data-model-fragments#serializing). What's probably going on is that the fragments are not using your application serializer at all. The readme describes how to create and register a fragment serializer base class.
