### ISSUE TITLE
Unable to copy a fragment

### ISSUE THREAD

**Issue by louy** [lytics/ember-data.model-fragments#98]
I'm trying to clone a DS.Model instance. When I use get and set for copying fragments I get the following error:
> "Assertion Failed: Fragments can only belong to one owner, try copying instead"

If I use `Ember.copy` I get this:
> "Assertion Failed: Cannot clone an Ember.Object that does not implement Ember.Copyable"

What is the correct way to achieve what I want?

**Comment by slindberg** [comment]
Can you provide more context or a jsbin or a failing test case? I'm afraid [the test for this](https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/tests/unit/fragment_test.js#L38-L42) is a bit lacking, but cursory inspection shows that this is working.

Note that copying fragments with nested fragments [probably won't work](https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/model.js#L175), but it shouldn't throw that `Cannot clone an Ember.Object ...` error.

**Comment by louy** [comment]
Hi @slindberg,
I believe it's the latter, nested fragments. I'll come up with an implementation for this and send you a PR. Thanks!

**Comment by louy** [comment]
Just realized that I had a fully-functional copy function for ages!
I should've just used it recursively instead of `Ember.copy`.

Here you go:


    function copyFragment(fragment) {
      return function() {
        var store = Ember.get(this, 'store');
        var type = store.modelFor(this.constructor);

        var newFragment = this.store.createFragment(type);

        Ember.get(this.constructor, 'attributes').forEach(function(attribute) {
          if( attribute.type === 'fragment' ) {
            if( attribute.kind === 'hasMany' ) {
              newFragment.set(attribute.name, this.get(attribute.name).map(copyFragment));
            } else {
              newFragment.set(attribute.name, copyFragment( this.get(attribute.name) ));
            }
          } else {
            newFragment.set(attribute.name, this.get(attribute.name));
          }
        }.bind(this));

        return newFragment;
      }.apply(fragment);
    }

**Comment by louy** [comment]
My issue was that I was calling `Ember#copy` on an array, the solution was to use `Array#map(copyFragment)`.

**Comment by danielspaniel** [comment]
For model with attributes that are fragmentArray's 

doing:
```js
let attrs = model.toJSON();
let copy = store.createRecord(modelName, attrs );
```
will copy those fragment arrays without the issue of setting the owner and whatnot
