### ISSUE TITLE
Uncaught TypeError: Cannot read property '_unhandledEvent' of undefined with Ember Data 1.0.0-beta.19

### ISSUE THREAD

**Issue by GeoffreyBooth** [lytics/ember-data.model-fragments#99]
When upgrading Ember Data to 1.0.0-beta.19, this error appears (from `ember-data.model-fragments.js:98`):
```
Uncaught TypeError: Cannot read property '_unhandledEvent' of undefined
```
And Ember Data Model Fragments fails to load, which causes other errors to be thrown. 

See jsbin: http://emberjs.jsbin.com/hafaso/1/edit?html,js,console. Change Ember Data from beta.19 to beta.18 (HTML tab line 12) and the error goes away.

**Comment by slindberg** [comment]
I'm aware of the issue; this is unfortunately just the tip of the iceberg. The beta.19 release shifted around internal APIs in preparation for 1.0, and it will take a considerable amount of effort to maintain compatibility.

I'm currently in the process of a near-full rewrite to provide support for 1.0, so it's possible that MF will never support beta.19 due to my limited bandwidth.

**Comment by jevanlingen** [comment]
Are there any plans for support for beta 19? Or will the next version just support Ember Data 1.0?

**Comment by slindberg** [comment]
I'm currently working against the 1.13 release series, although it's possible that the update to that version will be compatible with beta-19.

**Comment by jevanlingen** [comment]
Ember Data 1.13 is fine too, I will just upgrade from beta-18 tot 1.13. No problem!

**Comment by jevanlingen** [comment]
Is there an ETA for next version?

**Comment by herczyn** [comment]
We are moving with our app to the new ember and ember data and need this update very much... Is there any way we could help You?

**Comment by slindberg** [comment]
Sorry for the delay all, recent changes have made the upgrade difficult. Unfortunately I don't think there's any way to help @herczyn, thanks for the offer.

**Comment by knownasilya** [comment]
Any progress? :smile_cat:

**Comment by slindberg** [comment]
Thanks for your patience everyone, I was able to get tests passing this weekend in #109. This update was very invasive, and so I would appreciate if anyone waiting on an upgrade could test against that PR. I've published the distribution files to the [`tmp-dist`](https://github.com/lytics/ember-data.model-fragments/tree/tmp-dist) branch, so you can install the package directly without having to clone and build:

```sh
$ bower install ember-data.model-fragments#tmp-dist
```

**Comment by devinus** [comment]
Very exciting @slindberg :beers:

**Comment by workmanw** [comment]
Indeed! I'm still on ember-data beta 15 for the moment, but it's great to know this will be available when I can slot it in time to upgrade.

**Comment by jevanlingen** [comment]
Gonna update to Ember, Ember Data and Ember cli 1.13 + using the `tmp-dist`Data Fragment. Hope everything will work out fine. Thanks for the update @slindberg!

Btw, wouldn't it be better to give your next release also v1.13 to stay in sync with al other Ember projects (I know this is not a core project, but it's a project that's likely to change every time when Ember got a new version)?

**Comment by devinus** [comment]
I know my opinion on this wont matter much here, but I hate the fact that projects other than Ember and Ember Data are adopting this versioning pattern. It's **not** semver compliant and only allows packages other than Ember to update their *patch* version. I think it adds more confusion than it helps. Is ember-data@1.13.5 compatible with ember@1.13.4? Who knows unless you read a single blog post on emberjs.com...

**Comment by knownasilya** [comment]
@devinus You should always be on the latest patch version, since those are bug fixes, and semver guarantees (as much as humanly possible) that the changes in the patch are fixes and not something that will make one version incompatible. 

The real value is in the major.minor version numbers, since then Ember Data can say yes we use the new computed property syntax because Ember 1.13 does.

**Comment by devinus** [comment]
@knownasilya Except that a library can now never have a major or minor version change to signify what they are supposed to signify according to semver. They can only ever bump the patch version. It's not semver.

**Comment by knownasilya** [comment]
Yes that is true, they have to wait till the next minor version to add new features. I think that's the idea, if you buy into this as a library author (I'm not, because I want the flexibility to not wait for Ember).
